export const SET_START_TIME = 'setStartTime'
export const START_WORKOUT = 'startWorkout'
export const SEND_REP = 'sendRep'
export const SKIP_EXERCISE = 'skipExercise'
export const CHANGE_EXERCISE = 'changeExercise'
export const CHANGE_SET = 'changeSet'
export const SET_COMPLETED = 'setCompleted'
export const SET_END_TIME = 'setEndTime'
