name: Frontend CI Deployment
on: 
  push:
    paths:
      - 'frontend/**.vue'
jobs:
  Build-Backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/vuetodo/frontend
    steps:
      - name: Checkout to main
        run: git checkout main
      - name: Pull changes
        run: git pull
      - name: Pull changes from npm
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Build frontend
        run: npm run build
