name: Build Frontend Pipeline
on: 
  push:
    branches: 
      - main
    paths:
      - 'src/**.vue'
      - '/**.ts'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build-Frontend:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:    
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: env.REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}/frontend:latest
          labels: 
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.ref.name=${{ steps.vars.outputs.short_ref }}


  
