name: Frontend CI testing
on: 
  push:
    branches-ignore: 
      - main
    paths:
      - 'frontend/**.vue'
      - 'frontend/**.ts'
jobs:
  Test-Frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/vuetodo/frontend
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1

      - name: Pull changes from npm
        run: npm install

      - name: Run tests
        run: npm run test
